### ISSUE TITLE
unable to connected in paired device

### ISSUE THREAD

**Issue by sarathi1989** [janosgyerik/bluetoothviewer#25]
I got following error while connect in the paired devices

02-28 17:32:16.628 21223-21620/net.bluetoothviewer E/BluetoothDeviceConnector: read failed, socket might closed or timeout, read ret: -1
                                                                               java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                                   at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:567)
                                                                                   at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:544)
                                                                                   at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:319)
                                                                                   at net.bluetoothviewer.BluetoothDeviceConnector$ConnectThread.run(BluetoothDeviceConnector.java:258)

**Comment by nitinaid** [comment]
Change to `public ConnectThread(BluetoothDevice device) throws SecurityException, NoSuchMethodException, IllegalArgumentException, IllegalAccessException, InvocationTargetException {
            mmDevice = device;
            BluetoothSocket tmp = null;

            Log.i(TAG, "calling device.createRfcommSocket with channel " + CHANNEL + " ...");
            try {
                UUID uuid = UUID.fromString("00001101-0000-1000-8000-00805f9b34fb");
                tmp = device.createRfcommSocketToServiceRecord(uuid);
            } catch (IOException e) {
                Log.e(TAG, e.getMessage(), e);
            }

            mmSocket = tmp;
        }`

it work for me

**Comment by janosgyerik** [comment]
Thanks @nitinaid but from where did you get the UUID `00001101-0000-1000-8000-00805f9b34fb` ?
